### ISSUE TITLE
Missing required parameter - api_key

### ISSUE THREAD

**Issue by EricHype** [cloudinary/cloudinary_ios#77] opened 2017-03-03 06:36 UTC
Hello,

I'm attempting to do a signed upload and I'm running in to the following 

Error Domain=com.cloudinary.error Code=400 "(null)" UserInfo={message=Missing required parameter - api_key}

The code is as follows:

```
guard let signature = signature else { return }
let num_timestamp = NSNumber(value: signature.timestamp!)
        
        
let config = CLDConfiguration(cloudName: signature.cloud_name!, apiKey: signature.api_key, apiSecret: nil)
let cloudinary = CLDCloudinary(configuration: config)
let cld_signature = CLDSignature(signature: signature.signature!, timestamp: num_timestamp)
let params = CLDUploadRequestParams()
let imageData: Data = UIImagePNGRepresentation(image)!
params.setSignature(cld_signature)
ProgressUtility.loading(self.view, "Uploading to image Service")
        
cloudinary.createUploader().signedUpload(data: imageData, params: params, progress: { (progress) in
            // Handle progress
}) { (response, error) in
            // Handle response
            ProgressUtility.dimiss(self.view)
                    
            guard let url = response?.url else { print("no url in image result"); return }
            self.trainerVM.imageUrl = url
}


```

I've triple checked, my API key value is correct.

**Comment by oferZemingo** [comment] 2017-03-03 18:18
There's an issue when using CLDSignature, to workaround it don't set the signature using CLDSignature, instead set the signature params and the api-key manually:
```
let params = CLDUploadRequestParams()
params.setParam("api_key", YOUR_API_KEY)
params.setParam("signature", YOUR_SIGNATURE)
params.setParam("timestamp", YOUR_TIMESTAMP_AS_STRING)
cloudinary.createUploader().signedUpload(...)
```

**Comment by EricHype** [comment] 2017-03-03 21:47
Hello oferZemingo,

Using a workaround as you described only leads to another issue:

Error Domain=com.cloudinary.error Code=401 "(null)" UserInfo={message=Invalid Signature c7bcdace47dcdedde6302f9a4686bcad166da90c. String to sign - 'timestamp=1488577356'.}

Generating the signature is like this on my server - which appears to be correct per the cloudinary documentation:

"timestamp=" + timestampInSeconds.toString() + cloudinary_api_secret;
var shaString = sha1(stringToSHA);

**Comment by oferZemingo** [comment] 2017-03-03 22:20
I don't see something wrong with what you're doing, just make sure you're using the same timestamp as used to generate the signature on your server and that you're not setting any more params other than the timestamp, signature and api_key, if you are they need to be part of your "stringToSHA" variable on your server.
The SDK has a public function that generates a signature the way you should on the server side, you can try using it and compare the result with your server generated signature (using the same params of course):
```
cloudinarySignParamsUsingSecret(["timestamp" : your_timestamp_as_string], cloudinaryApiSecret: your_cloudinary_api_secret)
```

**Comment by EricHype** [comment] 2017-03-03 23:27
Ok, I didn't change anything and it suddenly started working... I don't know how to react to that.

**Comment by 0xc00010ff** [comment] 2017-04-07 06:20
Seeing this problem as well. Swift 3.1. 
Double checked that hardcoding the API keys and secret works. 
Double checked that the Node SDK was producing the same SHA1 hash with the timestamp and api_secret.

**Comment by 0xc00010ff** [comment] 2017-04-07 06:26
`    fileprivate func uploadImageData(_ imageData: Data, signature: CLDSignature, completion: @escaping UploadToUrlClosure)
    {
        let config = CLDConfiguration(cloudName: CLOUDINARY_CLOUD_NAME, apiKey: CLOUDINARY_PUBLIC_KEY, apiSecret: nil)
        let cloudinary = CLDCloudinary(configuration: config)
        let params = CLDUploadRequestParams()
        params.setSignature(signature)
        
        // upload the god damn thing
        cloudinary.createUploader().signedUpload(data: imageData, params: params, progress: { (progress) in
            
            // log progress
            print("\(progress.fractionCompleted * 100)%")
            
        }, completionHandler: { (result, error) in
            
            // make sure there was no error
            guard error == nil else
            {
                print("Error uploading to Cloudinary: \(error!)")
                completion(nil, error)
                return
            }
            
            // make sure there's a url
            guard let url = result?.url else
            {
                let error = NSError(code: 557, message: "Cloudinary response error: no URL")
                print(error)
                completion(nil, error)
                return
            }
            
            // success
            print("Cloudinary upload complete!")
            
            completion(url, nil)
        })
    }`

**Comment by 0xc00010ff** [comment] 2017-04-07 06:39
This works, per @oferZemingo. Thanks. The problem is, I was trying to make the case for converting from S3 to Cloudinary for a _very_ large operation, and this in production kind of irks the shit out of me. Would love to know if I'm missing something or if there's a known fix. 

Working code: 

```Swift
fileprivate func uploadImageData(_ imageData: Data, signature: CLDSignature, completion: @escaping UploadToUrlClosure)
{
    let config = CLDConfiguration(cloudName: CLOUDINARY_CLOUD_NAME, apiKey: CLOUDINARY_PUBLIC_KEY, apiSecret: nil)
    let cloudinary = CLDCloudinary(configuration: config)
    let params = CLDUploadRequestParams()
    params.setParam("api_key", value: CLOUDINARY_PUBLIC_KEY)
    params.setParam("signature", value: signature.signature)
    params.setParam("timestamp", value: signature.timestamp.stringValue)
    
    // upload the image data
    cloudinary.createUploader().signedUpload(data: imageData, params: params, progress: { (progress) in
        
        // log progress
        print("\(progress.fractionCompleted * 100)%")
        
    }, completionHandler: { (result, error) in
        
        // make sure there was no error
        guard error == nil else
        {
            print("Error uploading to Cloudinary: \(error!)")
            completion(nil, error)
            return
        }
        
        // make sure there's a url
        guard let url = result?.url else
        {
            let error = NSError(code: 557, message: "Cloudinary response error: no URL")
            print(error)
            completion(nil, error)
            return
        }
        
        // success
        print("Cloudinary upload complete!")
        
        completion(url, nil)
    })
}
```

**Comment by roeeba** [comment] 2017-10-03 12:01
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support at http://support.cloudinary.com or create a new ticket if you have any additional issues.

**Closed by roeeba** 2017-10-03 12:01 UTC
Labels: question

**Comment by onmyway133** [comment] 2018-03-15 09:58
Take a look at `CLDNetworkCoordinate.swift`, this function

```swift
    internal func upload(_ data: Any, params: CLDUploadRequestParams, extraHeaders: [String:String]?=[:]) -> CLDNetworkDataRequest {
        let url = getUrl(.Upload, resourceType: params.resourceType)
        let requestParams = params.signed ? getSignedRequestParams(params) : params.params
        var headers :[String : String] = getHeaders()
        headers.cldMerge(extraHeaders)
        return networkAdapter.uploadToCloudinary(url, headers: headers, parameters: requestParams,  data: data)
    }
```

```swift
fileprivate func getSignedRequestParams(_ requestParams: CLDRequestParams) -> [String : Any] {
        var params: [String : Any] = requestParams.params
        
        guard let apiKey = config.apiKey else {
            printLog(.error, text: "Must supply api key for a signed request")
            return params
        }
}
```

And look at `config.apiKey`. It is a `String`. In my case, I use `Int`, so I need to convert it to `String` to make it work

**Comment by roeeba** [comment] 2018-03-20 12:06
Hi @onmyway133, we're trying to understand the issue you're presenting. Can you please let us know how exactly can we help here? 
Thanks!
