### ISSUE TITLE
Cannot init CLUploader in Swift Anymore

### ISSUE THREAD

**Issue by mbalex99** [cloudinary/cloudinary_ios#21] opened 2015-08-03 11:38 UTC
I updated to the latest version and now I cannot initialize CLUploader 

      var cloudinary = CLCloudinary()
        cloudinary.config().setValue(Environment.sharedInstance.cloudinaryApiSecret, forKey: "api_secret")
        cloudinary.config().setValue(Environment.sharedInstance.cloudinaryApiKey, forKey: "api_key")
        cloudinary.config().setValue(Environment.sharedInstance.cloudinaryCloudName, forKey: "cloud_name")
        
        var uploader = CLUploader(cloudinary, delegate: self);
        uploader.upload(data, options: nil);

CLUploader in swift no longer has an init method or is broken?

**Comment by nadavofi** [comment] 2015-08-03 13:51
Hi, we might require some more information in order to identify the issue.
What is the error message you're seeing?
Also, did you use Cocoapods for creating the bridging headers to Swift?
Do Cloudinary-init and other methods work for you?

Thanks, Nadav.

**Comment by mbalex99** [comment] 2015-08-03 23:21
No I didn't use a bridging header. The newest cocoapods should have handle this correctly. The framework's reference generated this for the init.

    import UIKit

    //
    //  Uploader.h
    //  Cloudinary
    //
    //  Created by Tal Lev-Ami on 26/10/12.
    //  Copyright (c) 2012 Cloudinary Ltd. All rights reserved.
    //

    typealias CLUploaderCompletion = ([NSObject : AnyObject]!, String!, Int, AnyObject!) -> Void
    typealias CLUploaderProgress = (Int, Int, Int, AnyObject!) -> Void

    class CLUploader : NSObject {
    
    unowned(unsafe) var delegate: CLUploaderDelegate!
    var cloudinary: CLCloudinary! { get }
    
    init!(_ cloudinary: CLCloudinary!, delegate: CLUploaderDelegate!)
    func cancel()
    
    func upload(file: AnyObject!, options: [NSObject : AnyObject]!, withCompletion completionBlock: CLUploaderCompletion!, andProgress progressBlock: CLUploaderProgress!)
    func unsignedUpload(file: AnyObject!, uploadPreset: String!, options: [NSObject : AnyObject]!, withCompletion completionBlock: CLUploaderCompletion!, andProgress progressBlock: CLUploaderProgress!)
    func destroy(publicId: String!, options: [NSObject : AnyObject]!, withCompletion completionBlock: CLUploaderCompletion!, andProgress progressBlock: CLUploaderProgress!)
    func rename(fromPublicId: String!, toPublicId: String!, options: [NSObject : AnyObject]!, withCompletion completionBlock: CLUploaderCompletion!, andProgress progressBlock: CLUploaderProgress!)
    func explicit(publicId: String!, options: [NSObject : AnyObject]!, withCompletion completionBlock: CLUploaderCompletion!, andProgress progressBlock: CLUploaderProgress!)
    func addTag(tag: String!, publicIds: [AnyObject]!, options: [NSObject : AnyObject]!, withCompletion completionBlock: CLUploaderCompletion!, andProgress progressBlock: CLUploaderProgress!)
    func removeTag(tag: String!, publicIds: [AnyObject]!, options: [NSObject : AnyObject]!, withCompletion completionBlock: CLUploaderCompletion!, andProgress progressBlock: CLUploaderProgress!)
    func replaceTag(tag: String!, publicIds: [AnyObject]!, options: [NSObject : AnyObject]!, withCompletion completionBlock: CLUploaderCompletion!, andProgress progressBlock: CLUploaderProgress!)
    func text(text: String!, options: [NSObject : AnyObject]!, withCompletion completionBlock: CLUploaderCompletion!, andProgress progressBlock: CLUploaderProgress!)
    func multi(tag: String!, options: [NSObject : AnyObject]!, withCompletion completionBlock: CLUploaderCompletion!, andProgress progressBlock: CLUploaderProgress!)
    func generateSprite(tag: String!, options: [NSObject : AnyObject]!, withCompletion completionBlock: CLUploaderCompletion!, andProgress progressBlock: CLUploaderProgress!)
    
    func upload(file: AnyObject!, options: [NSObject : AnyObject]!)
    func unsignedUpload(file: AnyObject!, uploadPreset: String!, options: [NSObject : AnyObject]!)
    func destroy(publicId: String!, options: [NSObject : AnyObject]!)
    func rename(fromPublicId: String!, toPublicId: String!, options: [NSObject : AnyObject]!)
    func explicit(publicId: String!, options: [NSObject : AnyObject]!)
    func addTag(tag: String!, publicIds: [AnyObject]!, options: [NSObject : AnyObject]!)
    func removeTag(tag: String!, publicIds: [AnyObject]!, options: [NSObject : AnyObject]!)
    func replaceTag(tag: String!, publicIds: [AnyObject]!, options: [NSObject : AnyObject]!)
    func multi(tag: String!, options: [NSObject : AnyObject]!)
    func generateSprite(tag: String!, options: [NSObject : AnyObject]!)
    func text(text: String!, options: [NSObject : AnyObject]!)
    
    func deleteByToken(token: String!, options: [NSObject : AnyObject]!)
    func deleteByToken(token: String!, options: [NSObject : AnyObject]!, withCompletion completionBlock: CLUploaderCompletion!)
    }

     protocol CLUploaderDelegate : NSObjectProtocol {
    
    optional func uploaderProgress(bytesWritten: Int, totalBytesWritten: Int, totalBytesExpectedToWrite: Int, context: AnyObject!)
    optional func uploaderSuccess(result: [NSObject : AnyObject]!, context: AnyObject!)
    optional func uploaderError(result: String!, code: Int, context: AnyObject!)
    }

**Comment by mbalex99** [comment] 2015-08-04 08:25
Even with the bridging header, I cannot init the CLUploader.

**Comment by nadavofi** [comment] 2015-08-04 14:03
Can you please try following the setup described here:
https://github.com/cloudinary/cloudinary_ios/issues/20#issuecomment-118623673
A step-by-step documentation is available here:
https://github.com/AFNetworking/AFNetworking/wiki/Getting-Started-with-AFNetworking

This will seamlessly download and convert Cloudinary's API and set the required dependencies to your project. Let us know if this works for you.

**Comment by mbalex99** [comment] 2015-08-05 06:37
I've been doing that but the init method is now gone as of the last update. It won't compile!

**Comment by nadavofi** [comment] 2015-08-07 13:09
I couldn't reproduce the issue you're encountering.
Can you please share the versions for your Cocoapods, Cloudinary_ios lib & Xcode?
In addition to that, if you can provide an access to your project this could also be very helpful.
If privacy is an issue, you can share it via support@cloudinary.com (for Nadav)

**Comment by taragano** [comment] 2015-12-02 09:57
Closing this issue due to the time elapsed.
Please feel free to contact our support http://support.cloudinary.com or create a new ticket if you have any additional issues.

**Closed by taragano** 2015-12-02 09:57 UTC
Labels: question
