### ISSUE TITLE
Cache sets the wrong image sometimes

### ISSUE THREAD

**Issue by Felizolinha** [cloudinary/cloudinary_ios#105] opened 2017-09-20 10:20 UTC
In my project, we have a bunch of collection views, most with images coming from Cloudinary. For some reason, when I reload the collection views, there's a random chance that the images of cells will come up duplicated.
Steps to reproduce:
- Create a collection view with at least 2 cells.
- Each cell must have an image coming from cloudinary, different from eachother.
- Reload the collection view's data source many times, there will probably be cells with the same images set on them, even though they were all supposed to be different.

**Comment by roeeba** [comment] 2017-09-22 12:41
Hi @Felizolinha. To better understand the issue, can you please also share your code and some cloudinary image URLs for example, which is this issue is happening on?

**Comment by Felizolinha** [comment] 2017-10-29 23:44
Sorry for taking this long to answer, I haven't had time to create a project reproducing this issue by itself, but here's a GIF representing the bug. I'm sure that's a bug related to Cloudinary because this happens in every collection view we create in the app and use the cldSet function to set Cloudinary Images. I'll try to create a project reproducing this sometime next week.
![cloudinary-bug](https://user-images.githubusercontent.com/5050667/32149834-bfcf9444-bcf1-11e7-908b-33bdeb5d9554.gif)

**Comment by shirlymanor** [comment] 2017-10-30 18:00
@Felizolinha In order for us to reproduce this issue can you please share the relevant code?
If privacy is an issue, you're more than welcomed to open a ticket and we'll be happy to suggest specific advice for you.

**Comment by roeeba** [comment] 2017-12-05 09:38
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support at http://support.cloudinary.com or create a new ticket if you have any additional issues.

**Closed by roeeba** 2017-12-05 09:38 UTC
Labels: question
