### ISSUE TITLE
Can not install with pods.

### ISSUE THREAD

**Issue by j4nos** [cloudinary/cloudinary_ios#110] opened 2017-10-02 08:38 UTC
Done as how to said, and get this:

<img width="1440" alt="kepernyofoto 2017-10-02 - 10 36 34" src="https://user-images.githubusercontent.com/11924475/31069678-c788af3a-a75d-11e7-8300-b62e4bdb2012.png">

**Comment by roeeba** [comment] 2017-10-03 08:10
Hi, @j4nos. Can you please share more information? how can we reproduce this? did you use pods, manual installation or something else?

**Comment by Sethmr** [comment] 2017-10-14 18:14
The first is that Right now if you are using Swift 4, you need to do this:

  pod 'Cloudinary', '~> 2.0.2'

And then add this before the last end statement somewhere in the taret 'YourAppName' do:

post_install do |installer|
        installer.pods_project.targets.each do |target|
            if target.name == 'Cloudinary'
                target.build_configurations.each do |config|
                    config.build_settings['SWIFT_VERSION'] = '3.2'
                end
            end
        end
    end

Next, running this line from your project directory may clear up some of your issues for a pod install:

rm -rf ~/Library/Caches/CocoaPods; rm -rf Pods; rm -rf ~/Library/Developer/Xcode/DerivedData/*; pod deintegrate; pod setup; pod install;

**Comment by hanandev** [comment] 2017-10-17 07:39
Please update pods for swift 4 asap thanks in advance

**Comment by nitzanj** [comment] 2017-10-25 19:37
@hanandev Did you try Sethmr's solution? We may update to Swift 4.0 but since there's a quick workaround I can't guarantee it'll be anytime soon.

**Comment by hanandev** [comment] 2017-10-26 05:34
@nitzanj  Yes I have already implemented this thing in my project's pod file because I had some other libraries also which were not at swift4 but now almost all of the libraries are updated at swift4 and I was just waiting for cloudinary on swift4 because we used that in every where in our app to upload images on cloudinary server and infact I personally love cloudinary thanks for your prompt reply I will wait for the updated cool framework 💯 .

**Comment by Sethmr** [comment] 2017-10-30 14:17
Just because there is a "quick workaround", doesn't mean it isn't worth fighting for the respect of your iOS clientele.

**Comment by hanandev** [comment] 2017-11-01 05:39
@Sethmr The solution you suggested works perfectly I appreciate your post and agreed your point for quick workaround it works superbly.

**Comment by Sethmr** [comment] 2017-11-02 17:04
@hanandev It may work 'perfectly' on my computer, but other members of my teams environment are constantly having it throwing errors. I don't have time to debug everything with it. Every other SDK we use was updated about a month ago.

**Comment by ryana** [comment] 2017-11-03 20:48
I'm also seeing this error. `Use of unresolved identifier 'CLDUploadRequestParams'`

I tried Sethmr's fix to no avail.

Would love a proper fix as soon as possible. Debating between this and other options right now for a new project. We'd be a paying customer :)

**Comment by hanandev** [comment] 2017-11-06 12:08
@Sethmr  Please address this to your team members to do like this in your Podfile mentioned snippet below it will force all other pods targets to port on swift 4. Hope it helps 

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            if target.name == 'Cloudinary'
            config.build_settings['SWIFT_VERSION'] = '3.0'
            else
            config.build_settings['SWIFT_VERSION'] = '4.0'
            end
        end
    end
end

**Comment by TanelTeemusk** [comment] 2017-11-10 10:29
@hanandev post_install does not help in my case as the code will never reach that phase. It fails already when terminal window says Installing Cloudinary so as a result there is no Cloudinary folder inside Pods. We also tried to copy the folder in there from @Sethmr computer with no results.
I suspect it's something to do between cocoapods and cloudinary.

So all in all I've tried the following:
1. Complete deinstall and reinstall xcode on my computer (Also made sure there is only one version installed)
2. Removed all post_install items from podfile
3. Added Cloudinary line without version
4. Also tried to clean project, build folders and manually delete everything from Deriveddata many times
all of those result to the same error. 
I'll also attach a text file with a verbose update error I'm getting.

[cloudinary_pod_error.txt](https://github.com/cloudinary/cloudinary_ios/files/1460964/cloudinary_pod_error.txt)
This is the same error I'm getting on our project but currently this log is copied from CldTester project

Slowly running out of ideas to try right now. Let me know if you can help.
Thanks.

**Comment by Sethmr** [comment] 2017-11-10 21:01
We are very close to dropping Cloudinary now. We potentially could be a massive customer. I can't deal with this. 

Why would you have Alamofire as a Dependency? Writing network calls without Alamofire is not difficult at all and would make the integration of your framework so much easier. Alamofire is widely used, so you are forcing them to have a duplicate dependencies which is are prone to throwing errors in any kind of manual install. Cocoapods isn't an option because some computers just refuse to go as far as installing the pod. 

I have been fighting with Installing the SDK with git submodules for a while. I have gotten it working a couple times, but nothing consistent. I need a straightforward quick list of things to do that I can tell my employees and not worry about their projects being broken. Currently, there is no way I can do this. Everytime I reinstall my pods(with the manual cloudinary install), I'm left with trying to put my project together slowly and Alamofire dependecies wanting to fight with each other.

**Comment by roeeba** [comment] 2017-11-13 10:35
Hi @Sethmr. We share your struggle. The issue is not necessarily with Swift 4, but rather a more general (and very common) issue when integrating common Crypto with Swift libraries. That said, we're working on a better solution for common Crypto integration. Hopefully, this would be introduced soon.

**Comment by Sethmr** [comment] 2017-11-20 18:26
![screen shot 2017-11-20 at 1 21 40 pm](https://user-images.githubusercontent.com/10062416/33034584-49fe1d60-cdf6-11e7-8843-f06124f3bdaa.png)
Cloudinary just need to make iOS a first class citizen. Based on that image, you can tell it is at the bottom of their totem pole.

**Comment by Sethmr** [comment] 2017-11-20 19:39
[PhotoAlbumApp.zip](https://github.com/cloudinary/cloudinary_ios/files/1488890/PhotoAlbumApp.zip)

I cleaned up the demo project for an easier read if your iOS guy wants a copy.

**Comment by roeeba** [comment] 2017-11-21 13:07
Thank you for sharing @Sethmr. In regards to your previous comment - the order in which the different SDKs are sorted in the screenshot you shared is completely arbitrary. We do put a lot of efforts to constantly improve our iOS library, and to resolve this specific issue in particular. 
We will update here on any progress done.

**Comment by roeeba** [comment] 2017-12-07 13:55
Hey Guys. We've just published a Release Candidate for our iOS library - `2.0.4-rc1`. This RC includes support for Swift 4 and the removal of CLDCryptoModule.
Could you please install it and let us know if you see any issues?

**Comment by Sethmr** [comment] 2017-12-07 18:24
@roeeba I am checking it out today.

**Comment by roeeba** [comment] 2018-02-01 14:13
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support at http://support.cloudinary.com or create a new ticket if you have any additional issues.

**Closed by roeeba** 2018-02-01 14:13 UTC
Labels: question
