### ISSUE TITLE
No such module 'CLDCrypto'

### ISSUE THREAD

**Issue by levantAJ** [cloudinary/cloudinary_ios#60] opened 2017-01-23 04:15 UTC
I'm using `cocoapods-1.2.0.rc.1`, and using Cloudinary 2.0.0, after run `pod install`, XCode throw error:  
`No such module 'CLDCrypto'` at `import CLDCrypto`
Please help me to give a solution? thx team

**Comment by tocker** [comment] 2017-01-23 06:39
Duplicate of #57. See #57 for an intermediate solution while we work to solve the issue.

**Closed by tocker** 2017-01-23 06:39 UTC
